rita_khg: homework_4 completed
eugene-okulik/Rita_Khegai pull request #3
Opened 2024-02-01 21:21 UTC by RitaKhegai

2024-02-02 15:26 UTC, eugene-okulik requested changes

2024-02-02 15:26 UTC, eugene-okulik commented on homework/rita_khegai/homework_4/homework_4.py
> +dict_['i am a tuple'] = 'Super puper'
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А у тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

Текст этого ключа намекает на то чем он должен быть )))

2024-02-04 10:38 UTC, RitaKhegai commented
готова)

2024-02-04 10:41 UTC, RitaKhegai commented
готова)

2024-02-05 10:36 UTC, eugene-okulik approved these changes

2024-02-05 10:36 UTC, merged