rita_khg: homework 5 completed
eugene-okulik/Rita_Khegai pull request #4
Opened 2024-02-06 10:14 UTC by RitaKhegai

2024-02-07 07:09 UTC, eugene-okulik requested changes

2024-02-07 07:09 UTC, eugene-okulik commented on homework/rita_khegai/homework_5/homework_5.py
> +country = person[4]
Обращение к элементам списка по индексу - это крайне не рекомендуемый способ взаимодействия со списком. Один из способов не делать это - распаковка. И именно этим способом нужно здесь воспользоваться. В видео занятия я показывал как это делается.

2024-02-07 07:09 UTC, eugene-okulik commented on homework/rita_khegai/homework_5/homework_5.py
> +f = f[3]
Две проблемы:
1. подход не универсален и для двух строк ты берешь элемент с индексом 2, а для еще одной берешь элемент с индексом 3
2. В задании было 

> С помощью срезов и метода index

Но у тебя нет ни срезов ни `index`.  
Да, эта задача правильнее решается с помощью `split()`, но задание - сделать это именно с помощью срезов и метода `index`

2024-02-08 18:19 UTC, RitaKhegai commented
спасибо за замечания.
 исправила

2024-02-09 09:15 UTC, eugene-okulik requested changes

2024-02-09 09:15 UTC, eugene-okulik commented on homework/rita_khegai/homework_5/homework_5.py
> +print(a.index('42'))
Если мы еще в момент написания программы знаем, что там число 42, то можем просто написать `print(42 + 10)`.  
Нужно как-то найти число в строках. Для этого нужно найти что у них общего: количество символов перед числом разное; количество символов в числе тоже разное; но зато в структуре строк есть что-то одинаковое.

2024-02-09 09:15 UTC, eugene-okulik commented on homework/rita_khegai/homework_5/homework_5.py
> +d = (a[20:])
Получается, ты сначала вычислила индексы и распечатала это, а потом руками их внесла?  
Ведь можно было
```python
a_index = a.index('42')
d = a[a_index:]
```
ну и скобки здесь не нужны.

2024-02-09 13:53 UTC, RitaKhegai commented on homework/rita_khegai/homework_5/homework_5.py
> +d = (a[20:])
принято

2024-02-10 07:24 UTC, eugene-okulik approved these changes

2024-02-10 07:24 UTC, merged