Rita Khegai: homework_8 completed
eugene-okulik/Rita_Khegai pull request #7
Opened 2024-05-22 12:48 UTC by RitaKhegai

2024-05-23 15:02 UTC, eugene-okulik requested changes

2024-05-23 15:02 UTC, eugene-okulik commented on homework/rita_khegai/homework_8/homework_8.2.py
Нужно было создать генератор и, получая числа из генератора, распечатать нужные. Хранить огромное количество данных в одной переменной - плохая практика. Правильнее для таких ситуаций создавать генератор. И тогда коод одновременно будет работать с одним числом и не будет никакой переменной, которая хранит всю последовательность чисел.

2024-06-02 11:51 UTC, RitaKhegai commented on homework/rita_khegai/homework_8/homework_8.2.py
Спасибо за обратную связь, поняла ошибку, исправила

2024-06-03 09:38 UTC, eugene-okulik approved these changes

2024-06-03 09:38 UTC, merged